import {
  pgTable,
  pgEnum,
  uuid,
  text,
  date,
  time,
  timestamp,
  integer,
  numeric,
  boolean,
  jsonb,
  inet,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

/**
 * YourWaves data model.
 *
 * Money is always an integer in minor units (see `price_*` below) — never a
 * float, never `numeric`. Booking days are always `date`, never `timestamp`;
 * see src/lib/dates.ts for why.
 *
 * The no-double-booking guarantee is NOT expressed here: it is a partial unique
 * index defined in drizzle/0001_booking_locking.sql, because Drizzle cannot
 * express a partial index over an enum list. That index — not application
 * code — is what makes overlapping bookings impossible.
 */

// --- Enums ------------------------------------------------------------------

/**
 * SRS 3.3 defines the customer-visible lifecycle:
 *   pending → confirmed → assigned → en_route → completed, plus cancelled.
 *
 * `holding` and `expired` are internal to the 10-minute checkout lock:
 * `holding` reserves the date while the customer pays; `expired` releases it.
 */
export const bookingStatus = pgEnum("booking_status", [
  "holding",
  "pending",
  "confirmed",
  "assigned",
  "en_route",
  "completed",
  "cancelled",
  "expired",
]);

/**
 * The statuses that occupy a date. Kept here as the single source of truth and
 * asserted against the database in tests, so this list and the partial unique
 * index in SQL can never silently diverge.
 */
export const BLOCKING_STATUSES = [
  "holding",
  "pending",
  "confirmed",
  "assigned",
  "en_route",
  "completed",
] as const;

export type BlockingStatus = (typeof BLOCKING_STATUSES)[number];
export type BookingStatus = (typeof bookingStatus.enumValues)[number];

export const actorType = pgEnum("actor_type", [
  "system",
  "admin",
  "customer",
  "driver",
]);

export const paymentStatus = pgEnum("payment_status", [
  "initiated",
  "paid",
  "failed",
  "refunded",
]);

export const notificationChannel = pgEnum("notification_channel", [
  "email",
  "whatsapp",
]);

export const notificationRecipientType = pgEnum("notification_recipient_type", [
  "customer",
  "admin",
  "driver",
]);

export const notificationStatus = pgEnum("notification_status", [
  "queued",
  "sent",
  "failed",
]);

// --- Dispatch recipients ----------------------------------------------------

/**
 * Anyone who can be sent a job by WhatsApp: the driver, the owner, a
 * supervisor, the technician.
 *
 * Was `drivers`, renamed in migration 0010. There is no driver login — the
 * `user_id` and `email` columns are gone with it — and a recipient flagged
 * `isDefault` is dispatched automatically the moment a booking is paid.
 */
export const dispatchRecipients = pgTable("dispatch_recipients", {
  id: uuid("id").primaryKey().defaultRandom(),
  fullName: text("full_name").notNull(),
  /** E.164. Unique since 0009: the number is the identity. */
  phone: text("phone").notNull(),
  role: text("role").notNull().default("driver"),
  /** Included on every newly confirmed booking, without an admin acting. */
  isDefault: boolean("is_default").notNull().default(false),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// --- Bookings ---------------------------------------------------------------

export const bookings = pgTable(
  "bookings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /**
     * Human-facing reference, e.g. "YW-2026-0417". Generated by
     * next_booking_reference() (see drizzle/0001_booking_locking.sql), which
     * restarts the counter each Qatar calendar year.
     */
    reference: text("reference").notNull().unique(),

    /** The FULL DAY being reserved. A calendar date — never a timestamp. */
    bookingDate: date("booking_date").notNull(),
    /** Customer's chosen setup time, Qatar wall clock. */
    preferredStart: time("preferred_start").notNull(),

    status: bookingStatus("status").notNull().default("pending"),
    /** Non-null only while status = 'holding'; enforced by a CHECK constraint. */
    holdExpiresAt: timestamp("hold_expires_at", { withTimezone: true }),

    customerName: text("customer_name").notNull(),
    /** E.164. */
    customerPhone: text("customer_phone").notNull(),
    customerEmail: text("customer_email"),
    phoneVerifiedAt: timestamp("phone_verified_at", { withTimezone: true }),

    addressLine: text("address_line").notNull(),
    area: text("area"),
    city: text("city"),
    /** Optional Google Maps link (SRS 3.1). */
    mapsUrl: text("maps_url"),
    lat: numeric("lat", { precision: 9, scale: 6 }),
    lng: numeric("lng", { precision: 9, scale: 6 }),

    notes: text("notes"),
    /** Language for ALL notifications sent to this customer. */
    locale: text("locale").notNull().default("ar"),

    // Money: minor units (1 QAR = 100 dirhams). Integers only.
    priceRental: integer("price_rental").notNull(),
    priceSetup: integer("price_setup").notNull(),
    priceDelivery: integer("price_delivery").notNull(),
    priceTotal: integer("price_total").notNull(),
    currency: text("currency").notNull().default("QAR"),

    assignedDriver: uuid("assigned_driver").references(
      () => dispatchRecipients.id,
      {
        onDelete: "set null",
      },
    ),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    // Availability lookups scan by date range and status.
    index("bookings_booking_date_idx").on(table.bookingDate),
    index("bookings_status_idx").on(table.status),
    index("bookings_hold_expires_at_idx").on(table.holdExpiresAt),
    index("bookings_customer_phone_idx").on(table.customerPhone),
  ],
);

// --- Booking events (immutable audit trail) ---------------------------------

export const bookingEvents = pgTable(
  "booking_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    bookingId: uuid("booking_id")
      .notNull()
      .references(() => bookings.id, { onDelete: "cascade" }),
    /** Null on the row recording creation. */
    fromStatus: bookingStatus("from_status"),
    toStatus: bookingStatus("to_status").notNull(),
    actorType: actorType("actor_type").notNull().default("system"),
    /** Admin/driver uuid, or a free-form id for customers. */
    actorId: text("actor_id"),
    metadata: jsonb("metadata").notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [index("booking_events_booking_id_idx").on(table.bookingId)],
);

// --- Blackout dates ---------------------------------------------------------

export const blackoutDates = pgTable("blackout_dates", {
  id: uuid("id").primaryKey().defaultRandom(),
  date: date("date").notNull().unique(),
  reason: text("reason"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// --- OTP verifications ------------------------------------------------------

export const otpVerifications = pgTable(
  "otp_verifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** E.164. */
    phone: text("phone").notNull(),
    /** Hash only. The plaintext code must never be persisted. */
    codeHash: text("code_hash").notNull(),
    attempts: integer("attempts").notNull().default(0),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    ip: inet("ip"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("otp_verifications_phone_idx").on(table.phone),
    index("otp_verifications_expires_at_idx").on(table.expiresAt),
  ],
);

// --- Payments ---------------------------------------------------------------

export const payments = pgTable(
  "payments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    bookingId: uuid("booking_id")
      .notNull()
      .references(() => bookings.id, { onDelete: "cascade" }),
    /** e.g. "skipcash". */
    provider: text("provider").notNull(),
    /** The provider's own transaction id. */
    providerRef: text("provider_ref"),
    /** Minor units, same convention as bookings.price_*. */
    amount: integer("amount").notNull(),
    currency: text("currency").notNull().default("QAR"),
    status: paymentStatus("status").notNull().default("initiated"),
    /** Verbatim provider webhook body, kept for dispute resolution. */
    rawPayload: jsonb("raw_payload"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  // A partial unique index on (provider, provider_ref) lives in
  // drizzle/0001_booking_locking.sql alongside the other partial indexes, so a
  // replayed provider webhook cannot create duplicate payment rows.
  (table) => [index("payments_booking_id_idx").on(table.bookingId)],
);

// --- Notifications (outbox) -------------------------------------------------

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    bookingId: uuid("booking_id").references(() => bookings.id, {
      onDelete: "cascade",
    }),
    channel: notificationChannel("channel").notNull(),
    recipientType: notificationRecipientType("recipient_type").notNull(),
    /** Email address or E.164 number. */
    recipient: text("recipient").notNull(),
    templateKey: text("template_key").notNull(),
    locale: text("locale").notNull().default("ar"),
    payload: jsonb("payload").notNull().default({}),
    status: notificationStatus("status").notNull().default("queued"),
    attempts: integer("attempts").notNull().default(0),
    /**
     * Raised by `resend_notification()` so a row that already burned its five
     * tries can genuinely go again when an admin asks.
     */
    maxAttempts: integer("max_attempts").notNull().default(5),
    lastError: text("last_error"),
    /**
     * Set when a worker takes the row and cleared when it finishes. A row that
     * still has this set long after `last_attempt_at` belonged to a worker that
     * died; `claim_notifications(limit, stale)` takes it back.
     */
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    lastAttemptAt: timestamp("last_attempt_at", { withTimezone: true }),
    /** Provider-side id of the delivered message, for support requests. */
    providerRef: text("provider_ref"),
    /** Doubles as the retry schedule: backoff pushes this into the future. */
    scheduledFor: timestamp("scheduled_for", { withTimezone: true })
      .notNull()
      .defaultNow(),
    sentAt: timestamp("sent_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    // The phase 7 worker polls exactly this: queued rows that are due.
    index("notifications_pending_idx").on(table.status, table.scheduledFor),
    index("notifications_booking_id_idx").on(table.bookingId),
    /**
     * The idempotency key from SRS 3.4: one message per booking, template and
     * recipient. Declared here so `pnpm db:generate` does not try to drop it;
     * the real definition is the partial index in
     * drizzle/0007_notifications.sql, which Drizzle cannot express (it is
     * `WHERE booking_id IS NOT NULL`).
     */
    uniqueIndex("notifications_dedupe_key").on(
      table.bookingId,
      table.templateKey,
      table.recipient,
    ),
  ],
);

// --- Settings (single row) --------------------------------------------------

export const settings = pgTable("settings", {
  /**
   * Constrained to 1 by a CHECK, so this table can only ever hold one row and
   * `select * from settings` is unambiguous.
   */
  id: integer("id").primaryKey().default(1),

  // Pricing, minor units.
  priceRental: integer("price_rental").notNull(),
  priceSetup: integer("price_setup").notNull(),
  priceDelivery: integer("price_delivery").notNull(),
  currency: text("currency").notNull().default("QAR"),

  /** Bookable setup times, Qatar wall clock, "HH:MM:SS". */
  availableStartTimes: text("available_start_times").array().notNull(),
  /** Minimum notice before the first slot of a day. */
  leadTimeHours: integer("lead_time_hours").notNull().default(24),
  /** How far ahead the calendar is open. */
  maxAdvanceDays: integer("max_advance_days").notNull().default(120),
  /** Checkout lock duration. */
  holdMinutes: integer("hold_minutes").notNull().default(10),

  adminNotificationEmails: text("admin_notification_emails")
    .array()
    .notNull()
    .default([]),
  /**
   * jsonb `[{en, ar}]` since migration 0012 — a text[] could only hold one
   * spelling, so an Arabic customer picked their area off an English chip.
   * The English name stays canonical: it is what `bookings.area` records.
   */
  serviceAreas: jsonb("service_areas")
    .$type<{ en: string; ar: string }[]>()
    .notNull()
    .default([]),

  /**
   * Terms & conditions, edited from the back office (migration 0014).
   *
   * Plain text, not HTML: an admin types into a textarea and the public page
   * renders paragraph-per-blank-line. Accepting markup here would mean an
   * admin could inject script into a customer-facing page, and a rich editor
   * is not what "type the terms in" needs.
   *
   * Empty English means the booking form shows no agreement tick at all —
   * asking someone to agree to nothing is worse than not asking.
   */
  termsEn: text("terms_en").notNull().default(""),
  /** Empty Arabic falls back to the English text rather than showing nothing. */
  termsAr: text("terms_ar").notNull().default(""),

  /**
   * Footer content overrides (migration 0015). Any key absent or empty falls
   * back to messages/*.json, so an untouched deployment renders the designed
   * footer and clearing a field restores the default rather than blanking it.
   */
  footer: jsonb("footer")
    .$type<Record<string, string>>()
    .notNull()
    .default({}),

  /**
   * FAQ (migration 0016), in display order. Empty falls back to the questions
   * in messages/*.json, so deleting every row restores the designed set rather
   * than emptying the section.
   */
  faq: jsonb("faq")
    .$type<
      {
        questionEn: string;
        questionAr: string;
        answerEn: string;
        answerAr: string;
      }[]
    >()
    .notNull()
    .default([]),

  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// --- Inferred types ---------------------------------------------------------

export type Booking = typeof bookings.$inferSelect;
export type NewBooking = typeof bookings.$inferInsert;
export type DispatchRecipient = typeof dispatchRecipients.$inferSelect;
export type Settings = typeof settings.$inferSelect;
export type BlackoutDate = typeof blackoutDates.$inferSelect;
export type Payment = typeof payments.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type BookingEvent = typeof bookingEvents.$inferSelect;
